backend:
  name: git-gateway
  branch: master
collections:
  - label: 'Globals'
    name: 'globals'
    files:
      - label: 'Site Copy (EN)'
        name: 'en_copy'
        file: 'src/_data/en_copy.json'
        fields::
          - { label: 'Switch Locales - Label', name: 'locales_label', widget: 'string' }
          - { label: 'Switch Locales - URL', name: 'locales_url', widget: 'string' }
      - label: 'Site Copy (FA)'
        name: 'fa_copy'
        file: 'src/_data/fa_copy.json'
        fields::
          - { label: 'Switch Locales - Label', name: 'locales_label', widget: 'string' }
          - { label: 'Switch Locales - URL', name: 'locales_url', widget: 'string' }
      - label: 'Site Metadata (EN)'
        name: 'en_site_metadata'
        file: 'src/_data/en_site_metadata.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Author', name: 'author', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
      - label: 'Site Metadata (FA)'
        name: 'fa_site_metadata'
        file: 'src/_data/fa_site_metadata.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Author', name: 'author', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
media_folder: 'src/images/uploads'
public_folder: 'images/uploads'
publish_mode: editorial_workflow
site_url: 'https://nazgolbagheri.com'
