backend:
  name: git-gateway
  branch: master
collections:
  - label: 'Globals'
    name: 'globals'
    files:
      - label: 'Site Metadata'
        name: 'site_metadata'
        file: 'src/_data/site_metadata.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
media_folder: 'src/images/uploads'
public_folder: 'images/uploads'
publish_mode: editorial_workflow
site_url: 'https://nazgolbagheri.com'
